name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
      - run: cd module_flutter && flutter pub get

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease
          
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "app/build/outputs/apk/release/mall_*.apk"
            token: ${{ secrets.GITHUB_TOKEN }}
            generateReleaseNotes: true

